if(APPLE)
   include_directories( /Developer/Headers/FlatCarbon )
   find_library(CORE_FOUNDATION_LIBRARY CoreFoundation)

   mark_as_advanced(CORE_FOUNDATION_LIBRARY)

   set(PLATFORM_LIBS ${CORE_FOUNDATION_LIBRARY})

   set(AVIAN_TARGET_FORMAT AVIAN_FORMAT_MACHO)
endif()

if(MSVC)
	set(PLATFORM_CXX_FLAGS "/W4")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SAFESEH:NO")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SAFESEH:NO")
  set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SAFESEH:NO")
else()
	set(PLATFORM_CXX_FLAGS "-Wall -Werror -fno-exceptions -std=c++0x")
  set(PLATFORM_LIBS ${PLATFORM_LIBS} pthread dl)
endif()

find_package(ZLIB REQUIRED)
include_directories(${ZLIB_INCLUDE_DIRS})

if(WIN32)
  set(PLATFORM_JAVA_HOME_INCLUDES $ENV{JAVA_HOME}/include/win32)
  set(PLATFORM_GRADLE_COMMAND "${CMAKE_SOURCE_DIR}/gradlew.bat")
  set(AVIAN_TARGET_FORMAT AVIAN_FORMAT_PE)
else()
  set(PLATFORM_GRADLE_COMMAND "${CMAKE_SOURCE_DIR}/gradlew")
endif()

if(LINUX)
  set(AVIAN_TARGET_FORMAT AVIAN_FORMAT_LINUX)
  set(PLATFORM_JAVA_HOME_INCLUDES $ENV{JAVA_HOME}/include/linux)
endif()

if(APPLE)
  set(PLATFORM_JAVA_HOME_INCLUDES $ENV{JAVA_HOME}/include/darwin)
endif()

if(CMAKE_SIZEOF_VOID_P MATCHES 4)
  set(TARGET_BYTES_PER_WORD 4)
  set(AVIAN_TARGET_ARCH AVIAN_ARCH_X86_64)
else()
  set(TARGET_BYTES_PER_WORD 8)
  set(AVIAN_TARGET_ARCH AVIAN_ARCH_X86)
endif()